filename:
  obsfits:   Cloverleaf_rob0_CO_3-2_mom0_-500to500.fits
  noisefits: Cloverleaf_rob0_CO_3-2_mom0_-500to500_noise.fits
  psffits:   psf.fits
  maskfits:  mask.fits
  input_b:   Akhunov.input   # glafic input (before optimization)
  input_a:   Akhunov_i.input # glafic input (after optimization for image plane)
  input_as:  Akhunov_s.input # glafic input (after optimization for source plane)
  optfile:   Akhunov_optresult.dat  # file suffix for optimized result
  imgfits:   Akhunov_image.fits
  srcfits:   Akhunov_source.fits
  resfits:   Akhunov_residual.fits
  imgout:    imagelist.png

path:
  glafic: /Users/tsuyoshi/Software/Glafic/glafic

primary_params:
  omega:     0.308
  lambda:    0.692
  weos:      -1.0
  hubble:    0.678
  zl:        1.95
  prefix:    Akhunov
  xmin:      -2.514375845630348
  ymin:      -2.525500073621787
  xmax:      2.4906241543699115
  ymax:      2.4794999263784727
  pix_ext:   0.077
  pix_poi:   0.2
  maxlev:    6

secondary_params:
  galfile:        galfile.dat
  srcfile:        srcfile.dat
  ran_seed:       -1234
  outformat_exp:  1
  flag_hodensity: 0
  hodensity:      200.0
  gnfw_usetab:    1
  ein_usetab:     1
  nfw_users:      0
  flag_extnorm:   0
  chi2_checknimg: 0
  chi2_splane:    1
  chi2_usemag:    0
  chi2_restart:   -1
  obs_gain:       3.0
  obs_ncomb:      1
  obs_readnoise:  10.0
  skyfix:         0
  skyfix_value:   10000000000.0
  psfconv_size:   0.034
  seeing_sub:     1
  flag_srcsbin:   1
  srcsbinsize:    20.0
  flag_mcmcall:   0
  addwcs:         0
  wcs_ra0:        136.916758333   # to be updated
  wcs_dec0:       -0.699944444444 # to be updated
  ovary:          0
  lvary:          0
  wvary:          0
  hvary:          0

user_params:
  zs:        2.558 # user-defined
  pix_ext_s: 0.025 # user-defined
  mask:      False

model:
  lens: |-
    lens   sie    2.07188510e+02 -0.1776988  0.06499971 0.32 -39.7 0  0
    lens   sie    1.70672461e+02 -1.458425   4.5250     0    0     0  0
    lens   pert   2.558          -0.1776988  0.06499971 0.13 44.7  0  0
  source: |-
    extend gauss  2.558 1.0795 -7.099600e-01 -2.532900e-01 0 0 0.0807 0

optimization:
  lens: |-
    0 0 0 0 0 0 0
    0 0 0 0 0 0 0
    0 0 0 0 0 0 0
  source: |-
    0 1 1 1 1 1 1 0