filename:
  obsfits:   Cloverleaf_rob0_CO_3-2_mom0_-500to500.fits
  noisefits: Cloverleaf_rob0_CO_3-2_mom0_-500to500_noise.fits
  psffits:   psf.fits
  maskfits:  mask_glafic.fits
  priorfile: priorfile.dat
  input_b:   .input   # glafic input (before optimization)
  input_a:   _i.input # glafic input (after optimization for image plane)
  input_as:  _s.input # glafic input (after optimization for source plane)
  optfile:   _optresult.dat  # file suffix for optimized result
  imgfits:   _image.fits
  srcfits:   _source.fits
  resfits:   _residual.fits
  imgout:    result.png
  statout:   stat.dat

path:
  glafic: /Users/tsuyoshi/Software/Glafic/glafic

primary_params:
  omega:     0.308
  lambda:    0.692
  weos:      -1.0
  hubble:    0.678
  zl:        1.95
  prefix:    3d_0km_s
  xmin:      -2.514375845630348
  ymin:      -2.525500073621787
  xmax:      2.4906241543699115
  ymax:      2.4794999263784727
  pix_ext:   0.077
  pix_poi:   0.2
  maxlev:    6

secondary_params:
  galfile:        galfile.dat
  srcfile:        srcfile.dat
  ran_seed:       -1234
  outformat_exp:  1
  flag_hodensity: 0
  hodensity:      200.0
  gnfw_usetab:    1
  ein_usetab:     1
  nfw_users:      0
  flag_extnorm:   0
  chi2_checknimg: 0
  chi2_splane:    1
  chi2_usemag:    0
  chi2_restart:   -1
  obs_gain:       3.0
  obs_ncomb:      1
  obs_readnoise:  10.0
  skyfix:         0
  skyfix_value:   10000000000.0
  psfconv_size:   0.034
  seeing_sub:     1
  flag_srcsbin:   1
  srcsbinsize:    20.0
  flag_mcmcall:   0
  addwcs:         0
  wcs_ra0:        136.916758333   # to be updated
  wcs_dec0:       -0.699944444444 # to be updated
  ovary:          0
  lvary:          0
  wvary:          0
  hvary:          0

user_params:
  zs:        2.558 # user-defined
  pix_ext_s: 0.025 # user-defined
  mask:      False
  prior:     False

model:
  lens: |-
    lens   sie      2.715046e+02 -1.793847e-01  2.320515e-01  5.125672e-01  2.501758e+01  3.920558e-04  0.000000e+00
    lens   sie      1.409138e+02 -4.320866e-01  1.718002e-02  5.265276e-01  3.195574e+02  1.029527e-04  0.000000e+00
    lens   pert     2.557720e+00  1.211398e+00 -9.636310e-02  4.073439e-02  5.459401e+01  0.000000e+00 -1.788457e-02
  source: |-
    extend gauss  2.5577  2.263202e+00 -2.502798e-01  2.090043e-01  4.012548e-01  1.174098e+02  8.696545e-02  0.000000e+00
    extend gauss  2.5577  1.412935e-01 -2.188197e-01  1.198960e-01  9.025350e-01  1.874007e+02  5.000599e-02  0.000000e+00

optimization:
  lens: |-
    1 1 1 1 1 1 0
    1 1 1 1 1 1 0
    0 1 1 1 1 0 1
  source: |-
    0 1 1 1 1 1 1 0
    0 1 1 1 1 1 1 0
